/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package paquete;

import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import paquete.Utilidades;

/**
 *
 * @author User
 */
public class Home extends javax.swing.JPanel {
    private final JPanel Panelbody;
    private final int categoria;
    private String nombreGrado;
          
    // Crear una instancia de Dimension
    Dimension dimension = new Dimension(381, 291); // Ejemplo de ancho y alto 
    Dimension dimensionmax = new Dimension(431, 341);     
    private final String[] rutaImg;

    /** Creates new form Home
     * @param panelBody
     * @param indice
     */
    public Home(JPanel panelBody, int indice) {
        this.Panelbody = panelBody; // Asigna el panel recibido
        this.categoria = indice;
        
        // Obtener el nombre del grado desde JSONNavigator
        Object resultadogrado = JSONNavigator.acceder("grados", String.valueOf(indice), "nombre");
        
        // Validar que el resultado es un String
        String nombreGrado = (resultadogrado instanceof String) ? (String) resultadogrado : "Desconocido";

        System.out.println("Nombre del grado cargado: " + nombreGrado);        
                
        initComponents();
        //Main.instance.Panelbody
        
        JLabel[] images = new JLabel[] {imghm1, imghm2, imghm3, imghm4, imghm5, imghm6};
        rutaImg = Utilidades.CreateStringList("src/images/pics", nombreGrado, "png", images.length).toArray(String[]::new);
                
        for (int i = 0; i < rutaImg.length; i++) {
            final int finalIndex = i;
            //asignar imagen de ruta correspondiente con el label correspondiente
            Utilidades.SetImageLabel(images[i], rutaImg[i], dimension, true);
            //asignar eventos a cada label correspondiente
            
            // Agregar MouseListener
            images[i].addMouseListener(new MouseAdapter() {                
                @Override
                public void mouseClicked(MouseEvent e) {
                    // Acción al hacer clic
                    Game hm = new Game(finalIndex, categoria);
                    Utilidades.ShowPanel (Panelbody, hm);
                    // Aquí puedes añadir la lógica que necesites
                }
                @Override
                public void mouseEntered(MouseEvent e) {
                    // Acción al pasar el mouse sobre el JLabel
                    Utilidades.SetImageLabel(images[finalIndex], rutaImg[finalIndex],dimensionmax, true);
                }
                @Override
                public void mouseExited(MouseEvent e) {
                    // Acción al salir el mouse del JLabel
                    Utilidades.SetImageLabel(images[finalIndex], rutaImg[finalIndex], dimension, true);
                }
                @Override
                public void mousePressed(MouseEvent e) {
                    // Acción al presionar el mouse sobre el JLabel
                    Utilidades.SetImageLabel(images[finalIndex], rutaImg[finalIndex],dimension, true);
                }
                @Override
                public void mouseReleased(MouseEvent e) {
                    // Acción al liberar el mouse sobre el JLabel
                    Utilidades.SetImageLabel(images[finalIndex], rutaImg[finalIndex], dimensionmax, true);
                }
            });                               
        }                                                                       
    }
        
    
  
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelImages = new javax.swing.JPanel();
        imghm1 = new javax.swing.JLabel();
        imghm2 = new javax.swing.JLabel();
        imghm3 = new javax.swing.JLabel();
        imghm4 = new javax.swing.JLabel();
        imghm5 = new javax.swing.JLabel();
        imghm6 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1561, 878));
        setMinimumSize(new java.awt.Dimension(1561, 878));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1561, 878));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelImages.setMaximumSize(new java.awt.Dimension(1561, 878));
        PanelImages.setMinimumSize(new java.awt.Dimension(1561, 878));
        PanelImages.setOpaque(false);
        PanelImages.setPreferredSize(new java.awt.Dimension(1561, 878));
        PanelImages.setLayout(new java.awt.GridLayout(2, 3, -100, -50));

        imghm1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imghm1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pics/Grado0.png"))); // NOI18N
        imghm1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelImages.add(imghm1);

        imghm2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imghm2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pics/Grado1.png"))); // NOI18N
        imghm2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelImages.add(imghm2);

        imghm3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imghm3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pics/Grado2.png"))); // NOI18N
        imghm3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelImages.add(imghm3);

        imghm4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imghm4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pics/Grado3.png"))); // NOI18N
        imghm4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelImages.add(imghm4);

        imghm5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imghm5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pics/Grado4.png"))); // NOI18N
        imghm5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelImages.add(imghm5);

        imghm6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imghm6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pics/Grado5.png"))); // NOI18N
        imghm6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PanelImages.add(imghm6);

        add(PanelImages, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1561, 878));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelImages;
    private javax.swing.JLabel imghm1;
    private javax.swing.JLabel imghm2;
    private javax.swing.JLabel imghm3;
    private javax.swing.JLabel imghm4;
    private javax.swing.JLabel imghm5;
    private javax.swing.JLabel imghm6;
    // End of variables declaration//GEN-END:variables

}
